### ISSUE TITLE
incorrect Risk flags on capabilities causing security warnings in reports.

### ISSUE THREAD

**Issue by danmarsden** [Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites#26]
the capabilities user_favorites:addinstance, user_favorites:add, user_favorites:delete, user_favorites:view all seem to have the wrong riskbitmasks set.

after installing this plugin - the Moodle Security checks report shows big warnings about all the authenticated users being able to perform XSS - and I'm pretty sure this plugin doesn't have any emailing capability so the RISK_SPAM flag shouldn't be there either.

**Comment by gemguardian** [comment]
@luukverhoeven could you please check Dans comment and make the necessary change?

**Comment by luukverhoeven** [comment]
@gemguardian, we've made some modifications to the code. Could you please validate these changes? https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites/tree/86bwcn75d_riskbitflags

**Comment by gemguardian** [comment]
@luukverhoeven just to be sure, does the addinstance needs to Xss warning? You can add the block to a page, but you only add Moodle pages to the favorites. And yes in such a page there could be XSS but it not necessary caused by the block itself. 

I did not see any other issues, tested on M4.1 PHP8

![image](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block-user_favorites/assets/16559999/32996a89-1e90-437c-a7b9-6d1da05f4d88)

**Comment by gemguardian** [comment]
@luukverhoeven as discussed the flag stays, there is a risk that the title could contain XX-content. We could prevent this by using PARAM_TEXT instead off PARAM_RAW.

I will make a seperated issue for this, and will see if we will change this in the furture by ourself or someone sends in a pull request. I will close this issue as we made the correct changes in the new 4.1/4.2 release
